# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "KreyWatch"
name: KreyWatch
email: kreywatch@rixotstudio.cz
description: "Kreyren's contribution to PINE64 and maintainance of personal fork"
#baseurl: "kreywatch"
url: "http://quinalha.me"
#twitter_username: "gustavoquinalha"
github_username:  "kreyren"
color_theme:  "#b84dff"
color_text:  "#000"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
